### PR TITLE
Fix30ruling

### PR DESCRIPTION
**Pull request by aSemy**
I uncommented the code related to choosing the young/normal/research 30% ruling options and set it to fetch the data from data.json.

### CODE REVIEW

**Comment by stevermeister** [comment]
ok

**Comment by stevermeister** [comment]
does not work when you select "Other" option :(

**Comment by aSemy** [comment]
Hi @stevermeister, can you give an example of it not working please? Here's one where it does work. The percentage of the €50,000/year salary that's covered is 26%

http://thetax.nl/?year=2017&startFrom=Year&salary=50000&allowance=0&socialSecurity=1&retired=0&ruling=1&rulingChoice=normal

**Comment by stevermeister** [comment]
@aSemy sorry, already removed the comment, it was my issue

**Comment by aSemy** [comment]
@stevermeister Cool! Glad to hear it's working :)

**Pull request merged**
