### PR TITLE
Added a chart to show the how relative income is to tax ;)

### PR DESCRIPTION
**Pull request by AchoArnold**
- This PR also fixes 5 npm vulnerabilities.

### CODE REVIEW

**Comment by stevermeister** [comment]
could you add a screenshot how it looks to PR please?

**Comment by AchoArnold** [comment]
This is how it looks
Screenshot 2019-06-11 13 35 27

You can test it for yourself directly here https://deploy-preview-76--thetax.netlify.com/?year=2019&startFrom=Year&salary=36000&allowance=0&socialSecurity=1&retired=0&ruling=0&rulingChoice=normal

**Comment by stevermeister** [comment]
I've just played with checkboxes "30%" and "65" and found pretty strange behaviour, could you please check?

**Comment by AchoArnold** [comment]
Hello,

@stevermeister  I've fixed the issue you mentioned. https://deploy-preview-76--thetax.netlify.com/?year=2015&startFrom=Year&salary=36000&allowance=0&socialSecurity=1&retired=0&ruling=0&rulingChoice=normal

**Comment by stevermeister** [comment]
could you please also make the graph optional?

**Comment by AchoArnold** [comment]
Okay. I'll do that ;).

**Pull request closed without merging**
